### ISSUE TITLE
any chance of a ayu mojave theme

### ISSUE THREAD

**Issue by sseale-zz** [licatajustin/hyper-ayu#3]
I asked this dev as well https://github.com/libcy/ayu-adaptive. do love your hyper theme

**Comment by licatajustin** [comment]
Can you tell me a little more about `ayu-mojave` theme?

**Comment by sseale-zz** [comment]
oh sorry it is another theme located in that above `ayu-adaptive` just has the colors of the new mojave dark mode

**Comment by licatajustin** [comment]
@sseale, it actually wouldn't be that difficult if you wanted to fork this repository and try it on your own. For the most part, you would just be replacing [these color variables](https://github.com/licatajustin/hyper-ayu/blob/master/index.js#L2-L12) in the Hyper theme with [these from the Atom theme](https://github.com/libcy/ayu-adaptive/blob/master/build.js#L88-L105).

I'd be happy for you to give it a shot first via forking my repository -- if you get stuck I can submit a Pull Request and help you out 😄

**Comment by licatajustin** [comment]
Going to close this now. I hope to see something from you soon in regards to the `ayu-mojave` theme!
